GET http://localhost:8080/api/cart

###

POST http://localhost:8080/api/cart
Content-Type: application/json

{
    "_id": "raj",
    "items": [{"name":"belt"}, {"name": "band"}]
}

# 

###

GET http://localhost:8080/api/cart/user
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.YWRtaW4z.WMsxJwmFBHnjFO3oQOI8ms6pHaxcFyxF_K4AkZLOVA8

