POST http://localhost:8080/api/clothes
Content-Type: application/json

 {
    "gender": "M",
    "name": "Toothbrush2",
    "new": false,
    "sale": {
      "begin": false,
      "discount": 50
    }
  }

###

GET http://localhost:8080/api/clothes

###
GET http://localhost:8080/api/clothes/male

###
GET http://localhost:8080/api/clothes/female

###
GET http://localhost:8080/api/clothes/new

###
GET http://localhost:8080/api/clothes/sale